name: qr_code_scanner_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # scan QR Code
  flutter_barcode_scanner: ^1.0.1

  # create QR Code
  barcode_widget: ^1.5.0
  http: ^0.13.3
  flutter_launcher_icons: ^0.9.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"